name: "03 - pull request"

on: 
  pull_request:
    branches: 
      - main

jobs:
  afficher-info:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message de pr
        run: |
          echo "Pull request detecte"
          echo "Auteur : ${{ github.actor }}"
          echo "branch pr : ${{ github.ref_name }}"
          echo "cible : ${{ github.base_ref }}"